---
- name: "Obfuscation du mot de passe pour rclone"
  ansible.builtin.shell: |
    rclone obscure "{{ ovh_sftp_password }}"
  register: "setup_sftp_password_for_rclone"

- name: "[DEBUG] Information sur la connection SFTP"
  ansible.builtin.debug:
    msg:
      - "URL SFTP: {{ ovh_sftp_username }}@{{ ovh_sftp_hostname }}"
      - "Mot de passe SFTP: {{ ovh_sftp_password }}"
      - "Mot de passe SFTP (obfuscé): {{ setup_sftp_password_for_rclone.stdout }}"
  when: "debug_enabled"

- name: "[DEBUG] Information sur la base de donnée"
  ansible.builtin.debug:
    msg:
      - "Nom d'hôte: {{ database_hostname }}"
      - "Nom de la base de donnée: {{ database_name }}"
      - "Utilisateur de la base de donnée: {{ database_username }}"
      - "Mot de passe: {{ database_password }}"
  when: "debug_enabled"

- name: "Création d'un répertoire de travail"
  ansible.builtin.tempfile:
    state: "directory"
    prefix: "chevregrisette."
  register: "setup_build_dir"
